name = "goldberg"
uuid = "20eee39b-f8d4-41c7-9b7b-a3da60597ee7"
authors = ["Scott Moore"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
